### PR TITLE
Revert "updated sheetseetemplate.glitch.me link"

### PR DESCRIPTION
**Pull request by Paroan47**

### CODE REVIEW

**Review by faizwa — APPROVED** [review]

**Review by Pakon2543 — APPROVED** [review]

**Review by Pakon2543 — APPROVED** [review]

**Comment by Pakon2543** [comment]
@ @Paroan47 @Pakon2543 @konklone

**Comment by Pakon2543** [comment]
> _No description provided._

**Comment by Pakon2543** [comment]
https://github.com/jlord/sheetsee.js/pull/270#issuecomment-980773201

**Comment by Pakon2543** [comment]
#270 #192 #270 #271 #192 [https://github.com/jlord/sheetsee.js/pull/270#issuecomment-980773201](google-site-verification=woYNq8o-G4Gbgz6k_YfjpC7uyjkR5nQRLJdrYKMC5AM)

**Review by Pakon2543 — APPROVED** [review]

**Comment by huuduyentinh14020201** [comment]
https://github.com/jlord/sheetsee.js/pull/270

**Pull request closed without merging**
