### PR TITLE
updated sheetseetemplate.glitch.me link

### PR DESCRIPTION
**Pull request by todrobbins**
per updated info: https://twitter.com/jllord/status/1141364138083586050

👍

### CODE REVIEW

**Comment by jlord** [comment]
Thank you!!!

**Comment by Tomcherry117687** [comment]
approve-these-changes

**Comment by Saschaym** [comment]
todrobbins:patch-1

**Comment by Saschaym** [comment]
👍

**Review by Balmasexy — APPROVED** [review]
64d92fbd0898440d555e50feb70cdb36473d764b

**Review by Balmasexy — APPROVED** [review]

**Pull request merged**
